-- Cached KPI forecast points generated by ReportAgent forecast jobs.

CREATE TABLE kpi_forecast (
    id             UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    tenant_id      UNIQUEIDENTIFIER NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
    platform       NVARCHAR(32) NOT NULL,
    metric         NVARCHAR(64) NOT NULL,
    forecast_date  DATE NOT NULL,
    value          DECIMAL(18,2) NOT NULL,
    lower_bound    DECIMAL(18,2) NOT NULL,
    upper_bound    DECIMAL(18,2) NOT NULL,
    generated_at   DATETIMEOFFSET NOT NULL DEFAULT SYSDATETIMEOFFSET(),
    UNIQUE (tenant_id, platform, metric, forecast_date)
);

CREATE INDEX ix_kpi_forecast_tenant_metric_date
    ON kpi_forecast (tenant_id, metric, forecast_date, platform);

