lines = []
lines.append('using System.Security.Claims;')
lines.append('using Clawbot.Api.Auth;')
lines.append('using Clawbot.Api.Middleware;')
lines.append('using Clawbot.Domain.Conversations;')
lines.append('using Clawbot.Infrastructure.Auth;')
lines.append('using Clawbot.Infrastructure.Persistence;')
lines.append('using Clawbot.SharedKernel.Multitenancy;')
lines.append('using Microsoft.AspNetCore.Mvc;')
lines.append('using Microsoft.EntityFrameworkCore;')
lines.append('')
lines.append('namespace Clawbot.Api.Endpoints;')
lines.append('')
lines.append('public sealed record CreateNoteRequest(string Content, string? Type, string? CreatedByName);')
lines.append('public sealed record UpdateNoteRequest(string Content);')
lines.append('')
lines.append('public static class InboxNotesEndpoints')
lines.append('{')
