<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <InternalsVisibleTo Include="Clawbot.Infrastructure" />
    <InternalsVisibleTo Include="Clawbot.Domain.Tests" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Clawbot.SharedKernel\Clawbot.SharedKernel.csproj" />
  </ItemGroup>
</Project>
