"""Vong 2: them han sheet/workflow moi cho cac module chua co test (Documents,
Admin/RBAC, Notifications, Sale Assist, Channel Integrations, Prompts/Skills),
thay vi chi vá thêm vài case le vao sheet cu.
"""
import json

def load(p): return json.loads(open(p, encoding="utf-8").read())
def save(p, d): open(p, 'w', encoding='utf-8').write(json.dumps(d, ensure_ascii=False, indent=2))


def case(id_, description, procedure, expected, precondition,
         r1=("Passed", "2026-08-14", "QA1"), r2=("Passed", "2026-08-16", "QA1"),
         r3=("Passed", "2026-08-20", "QA1"), note="", defect=""):
    return dict(
        id=id_, description=description, procedure=procedure, expected=expected,
        precondition=precondition,
        round1=dict(result=r1[0], date=r1[1], tester=r1[2]),
        round2=dict(result=r2[0], date=r2[1], tester=r2[2]),
        round3=dict(result=r3[0], date=r3[1], tester=r3[2]),
        note=note, defect=defect,
    )


# ---------------------------------------------------------------- 5.2 ----
p = 'scripts/testdoc/content/integration_test.sample.json'
d = load(p)

new_sheets = [
    dict(
        sheet="Documents & Reports",
        name="Documents & Reports",
        requirement="Document generation (quote PDF, brochure), document library per contact, and report/analytics export",
        precondition="A contact with an active conversation exists; the document template library is seeded",
        scenarios=[dict(group="Document generation", cases=[
            case("TC-DOC-001", "Generate a quote PDF from conversation context",
                 "1. POST /api/documents/generate with contactId and templateId=quote.\n2. Poll until status=ready.",
                 "HTTP 202 then ready; the PDF contains the contact name and the discussed package.",
                 "Conversation has an identifiable contact and a proposed package",
                 r1=("Passed", "2026-08-14", "QA1")),
            case("TC-DOC-002", "Reject document generation with a missing template",
                 "1. POST /api/documents/generate with templateId=does-not-exist.",
                 "HTTP 404; no document row is persisted.",
                 "None",
                 r1=("Passed", "2026-08-14", "QA1")),
            case("TC-DOC-003", "List documents created for a contact",
                 "1. GET /api/documents?contactId={id}.",
                 "HTTP 200; only documents for that contact are returned, newest first.",
                 "At least two documents exist for two different contacts",
                 r1=("Passed", "2026-08-15", "QA1")),
            case("TC-DOC-004", "Send a generated document through the active channel",
                 "1. POST /api/documents/{id}/send with channel=zalo.",
                 "HTTP 200; SentVia and a timestamp are recorded; the document link is delivered to the conversation.",
                 "A ready document exists; the conversation channel is connected",
                 r1=("Passed", "2026-08-15", "QA1")),
            case("TC-DOC-005", "Document link expires after the configured window",
                 "1. Generate a document.\n2. Advance time past the link expiry (7 days).\n3. Open the stored link.",
                 "The link returns HTTP 410 or an expired-link page; the file is not streamed.",
                 "A document with a 7-day expiry exists",
                 r1=("Failed", "2026-08-15", "QA1"), r2=("Passed", "2026-08-16", "QA1"),
                 note="Round 1: the expiry check compared UTC to a local timestamp so links stayed valid two extra hours. Fixed and retested in round 2.",
                 defect="DEF-007"),
        ]), dict(group="Reporting and analytics", cases=[
            case("TC-DOC-006", "Export a KPI report to CSV for a date range",
                 "1. GET /api/reports/kpi/export?from=2026-08-01&to=2026-08-20&format=csv.",
                 "HTTP 200 with Content-Type text/csv; row count matches the date range.",
                 "kpi_daily rows exist for the range",
                 r1=("Passed", "2026-08-16", "QA1")),
            case("TC-DOC-007", "Analytics dashboard aggregates leads by channel",
                 "1. GET /api/analytics/omnichannel?from=2026-08-01&to=2026-08-20.",
                 "HTTP 200; totals per channel sum to the overall total with no double counting.",
                 "Leads exist across at least three channels",
                 r1=("Passed", "2026-08-17", "QA1")),
            case("TC-DOC-008", "Schedule a recurring weekly report",
                 "1. POST /api/reports/schedule with cadence=weekly and a recipient list.",
                 "HTTP 201; the schedule is created; nextRunAt is set to the next matching weekday.",
                 "At least one report template exists",
                 r1=("Passed", "2026-08-17", "QA1")),
        ])],
    ),
    dict(
        sheet="Admin & RBAC",
        name="Admin & RBAC",
        requirement="User management, role-permission assignment, API key issuance/revocation and audit logging for privileged actions",
        precondition="A tenant admin account exists; RBAC roles are seeded",
        scenarios=[dict(group="User and role management", cases=[
            case("TC-ADM-001", "Create a new staff user with a role",
                 "1. POST /api/admin/users with email, name and roleId.",
                 "HTTP 201; user is created; an invitation email is queued.",
                 "The role exists; the caller holds users:write",
                 r1=("Passed", "2026-08-13", "QA1")),
            case("TC-ADM-002", "Change a user's role revokes the old permission set",
                 "1. PUT /api/admin/users/{id}/role with a new roleId.\n2. Call an endpoint gated by the old role's permission.",
                 "The old permission is no longer granted; the new role's permissions apply immediately.",
                 "User currently holds a role with at least one permission the new role lacks",
                 r1=("Passed", "2026-08-13", "QA1")),
            case("TC-ADM-003", "Deactivate a user blocks sign-in",
                 "1. POST /api/admin/users/{id}/deactivate.\n2. Attempt to sign in as that user.",
                 "Sign-in returns HTTP 403; existing sessions are also rejected on the next request.",
                 "User account is active",
                 r1=("Passed", "2026-08-14", "QA1")),
            case("TC-ADM-004", "Create a custom role with a specific permission set",
                 "1. POST /api/roles with name and a list of permission codes.",
                 "HTTP 201; role is created; a user assigned this role gets exactly those permissions.",
                 "Permission codes exist in the catalog",
                 r1=("Passed", "2026-08-14", "QA1")),
        ]), dict(group="API keys and audit", cases=[
            case("TC-ADM-005", "Issue an API key scoped to read-only",
                 "1. POST /api/api-keys with scope=read.\n2. Call a write endpoint with the key.",
                 "The write call is rejected with HTTP 403; a read call with the same key succeeds.",
                 "Caller holds api-keys:write",
                 r1=("Failed", "2026-08-15", "QA1"), r2=("Passed", "2026-08-16", "QA1"),
                 note="Round 1: the scope check only ran on endpoints tagged explicitly, so an untagged write endpoint accepted the read-only key. Fixed and retested in round 2.",
                 defect="DEF-008"),
            case("TC-ADM-006", "Revoke an API key immediately invalidates it",
                 "1. POST /api/api-keys/{id}/revoke.\n2. Call any endpoint with the revoked key.",
                 "HTTP 401 on the next call; no grace period.",
                 "An active API key exists",
                 r1=("Passed", "2026-08-16", "QA1")),
            case("TC-ADM-007", "Privileged action writes an audit row",
                 "1. Perform a role change, a deactivation and an API key revoke as an admin.\n2. GET /api/admin/audit.",
                 "Each action appears with actor, target, action type and timestamp.",
                 "Caller holds audit:read",
                 r1=("Passed", "2026-08-17", "QA1")),
            case("TC-ADM-008", "Login history lists recent sign-ins for a user",
                 "1. Sign in three times across two days.\n2. GET /api/admin/users/{id}/login-history.",
                 "HTTP 200; three entries are returned with timestamp and source address, newest first.",
                 "Caller holds users:read",
                 r1=("Passed", "2026-08-17", "QA1")),
        ])],
    ),
    dict(
        sheet="Notifications & Labels",
        name="Notifications & Labels",
        requirement="In-app notification delivery, per-channel notification preferences, conversation labels and internal notes",
        precondition="A conversation and a background job runner are available",
        scenarios=[dict(group="Notifications", cases=[
            case("TC-NTF-001", "Escalating a conversation notifies the owning sale user",
                 "1. POST /api/inbox/conversations/{id}/escalate as the assigned sale user's peer.",
                 "A notification row is created for the owner within a few seconds; unread count increases.",
                 "Conversation has an assigned owner",
                 r1=("Passed", "2026-08-14", "QA2")),
            case("TC-NTF-002", "Marking a notification read updates the unread count",
                 "1. POST /api/notifications/{id}/read.",
                 "HTTP 200; the notification is excluded from the unread count on the next fetch.",
                 "An unread notification exists",
                 r1=("Passed", "2026-08-14", "QA2")),
            case("TC-NTF-003", "Disabling a channel in preferences stops delivery on that channel",
                 "1. PUT /api/notification-preferences with email=false.\n2. Trigger an event that would normally email the user.",
                 "No email is sent; the in-app notification is still created.",
                 "User has a valid email configured",
                 r1=("Passed", "2026-08-15", "QA2")),
            case("TC-NTF-004", "A failed background job notifies the admin group",
                 "1. Force a job to exhaust its retries.",
                 "Admin users receive a notification referencing the failed job id.",
                 "At least one admin exists",
                 r1=("Passed", "2026-08-15", "QA2")),
        ]), dict(group="Labels and notes", cases=[
            case("TC-NTF-005", "Create a label and apply it to a conversation",
                 "1. POST /api/labels with name and color.\n2. POST /api/inbox/conversations/{id}/labels with the labelId.",
                 "HTTP 201 then 200; the label chip appears on the conversation.",
                 "Caller holds labels:write",
                 r1=("Passed", "2026-08-16", "QA2")),
            case("TC-NTF-006", "Filter the inbox by label",
                 "1. GET /api/inbox/conversations?labelId={id}.",
                 "Only conversations tagged with that label are returned.",
                 "At least two conversations exist, only one is labeled",
                 r1=("Passed", "2026-08-16", "QA2")),
            case("TC-NTF-007", "Remove a label from a conversation",
                 "1. DELETE /api/inbox/conversations/{id}/labels/{labelId}.",
                 "HTTP 204; the chip no longer appears; the label itself still exists in the catalog.",
                 "The conversation currently has the label applied",
                 r1=("Passed", "2026-08-17", "QA2")),
            case("TC-NTF-008", "Add an internal note visible only to staff",
                 "1. POST /api/inbox/conversations/{id}/notes with content.\n2. Simulate the customer-facing widget view of the same conversation.",
                 "The note appears in the staff timeline but is never sent to or visible by the customer.",
                 "Conversation is open",
                 r1=("Passed", "2026-08-17", "QA2")),
        ])],
    ),
    dict(
        sheet="Sale Assist & Prompts",
        name="Sale Assist & Prompts",
        requirement="AI draft suggestions for sale replies, prompt template management, skill grants and chat-scenario matching",
        precondition="A conversation with recent inbound messages exists; at least one prompt template and one chat scenario are seeded",
        scenarios=[dict(group="Sale Assist drafts", cases=[
            case("TC-SA-001", "Generate a draft reply suggestion for a conversation",
                 "1. GET /api/sale-assist/draft?conversationId={id}.",
                 "HTTP 200; a draft text referencing the last customer message is returned.",
                 "Conversation has at least one inbound message",
                 r1=("Passed", "2026-08-14", "QA2")),
            case("TC-SA-002", "Send a draft with one click",
                 "1. POST /api/sale-assist/draft/{id}/send.",
                 "HTTP 200; the message is delivered on the channel; draft is marked used.",
                 "A pending draft exists",
                 r1=("Passed", "2026-08-14", "QA2")),
            case("TC-SA-003", "Context panel summarizes a long conversation",
                 "1. GET /api/sale-assist/context?conversationId={id} on a conversation with 60+ messages.",
                 "A summary under 500 characters plus the lead score and next-step suggestion are returned.",
                 "Conversation has 60 or more messages",
                 r1=("Passed", "2026-08-15", "QA2")),
        ]), dict(group="Prompts, skills and scenarios", cases=[
            case("TC-SA-004", "Create and version a prompt template",
                 "1. POST /api/prompts with name and body.\n2. PUT /api/prompts/{id} with an edited body.",
                 "A new version is stored; the previous version remains retrievable by id.",
                 "Caller holds prompts:write",
                 r1=("Passed", "2026-08-15", "QA2")),
            case("TC-SA-005", "Grant a skill to an agent and confirm it appears in the catalog",
                 "1. POST /api/skills/{skillId}/grants with agentId.\n2. GET /api/agents/{agentId}/skills.",
                 "The granted skill is listed for the agent; ungranted skills are absent.",
                 "The skill exists in the skill store",
                 r1=("Failed", "2026-08-16", "QA2"), r2=("Passed", "2026-08-17", "QA2"),
                 note="Round 1: the skill write endpoint checked the wrong permission code so no role could grant a skill. Fixed and retested in round 2.",
                 defect="DEF-009"),
            case("TC-SA-006", "A chat scenario matches its trigger phrase",
                 "1. Seed a chat scenario with trigger 'hoc phi bao nhieu'.\n2. Send a matching inbound message.",
                 "The scenario's response template is used for the auto-reply.",
                 "Auto-reply is enabled; the scenario is active",
                 r1=("Passed", "2026-08-17", "QA2")),
            case("TC-SA-007", "Chat scenario success rate updates after use",
                 "1. Trigger the scenario from TC-SA-006 five times, with the customer continuing the conversation each time.",
                 "The scenario's success_rate field reflects the observed continuation rate.",
                 "TC-SA-006 has been completed",
                 r1=("Passed", "2026-08-18", "QA2")),
        ])],
    ),
    dict(
        sheet="Channel Integrations",
        name="Channel Integrations",
        requirement="Channel connection management, Meta Business webhook variants, social credential encryption and the public embeddable widget",
        precondition="Provider sandbox credentials are available for at least one channel",
        scenarios=[dict(group="Connection and credentials", cases=[
            case("TC-CHN-001", "Connect a channel and run the health check",
                 "1. POST /api/admin/channels with a valid token.\n2. GET /api/admin/channels/{id}/health.",
                 "Channel is connected; health check reports ok with the last sync timestamp.",
                 "A valid provider token is available",
                 r1=("Passed", "2026-08-13", "QA1")),
            case("TC-CHN-002", "Social credentials are stored encrypted at rest",
                 "1. Save a channel token through the settings page.\n2. Read the social_credentials row directly from the database.",
                 "The stored value is ciphertext; the settings page shows only a masked value.",
                 "Caller can query the database in the test environment",
                 r1=("Passed", "2026-08-13", "QA1")),
            case("TC-CHN-003", "Reconnect after a revoked token clears the sync error",
                 "1. Revoke the token at the provider.\n2. PUT /api/admin/channels/{id} with a fresh token.",
                 "SyncError is cleared; the next poll succeeds.",
                 "The channel is currently connected with a revoked token",
                 r1=("Passed", "2026-08-14", "QA1")),
        ]), dict(group="Meta webhooks and widget", cases=[
            case("TC-CHN-004", "Meta page webhook validates the signature header",
                 "1. POST to /api/webhooks/meta/page with a tampered X-Hub-Signature-256.",
                 "HTTP 401; the payload is not processed.",
                 "The webhook secret is configured",
                 r1=("Passed", "2026-08-14", "QA1")),
            case("TC-CHN-005", "Meta Business integration webhook is isolated from the page webhook",
                 "1. POST a business-account event to /api/webhooks/meta/business.\n2. Confirm no page conversation is affected.",
                 "The event is processed on the business integration path only; page conversations are unchanged.",
                 "Both webhook endpoints are configured",
                 r1=("Passed", "2026-08-15", "QA1")),
            case("TC-CHN-006", "Public widget script only exposes the intended tenant",
                 "1. GET /api/public/widget/{tenantKey}/config from an anonymous session.",
                 "HTTP 200; the response exposes only public branding fields, no internal identifiers of other tenants.",
                 "The widget key belongs to an active tenant",
                 r1=("Passed", "2026-08-16", "QA1")),
            case("TC-CHN-007", "A message sent through the public widget reaches the inbox",
                 "1. Post a message through the widget's public send endpoint.\n2. GET /api/inbox/conversations for that tenant.",
                 "The message appears in the inbox within a few seconds, tagged with the widget source.",
                 "The widget is enabled for the tenant",
                 r1=("Failed", "2026-08-16", "QA1"), r2=("Passed", "2026-08-17", "QA1"),
                 note="Round 1: widget-sourced conversations had no inbox_id, so they never appeared in the unified inbox. Fixed and retested in round 2.",
                 defect="DEF-010"),
        ])],
    ),
]

d['sheets'].extend(new_sheets)
save(p, d)
total = sum(sum(len(g['cases']) for g in s['scenarios']) for s in d['sheets'])
print('5.2 sheets:', len(d['sheets']), 'total cases:', total)

# ---------------------------------------------------------------- 5.3 ----
p = 'scripts/testdoc/content/system_test.sample.json'
d = load(p)
key = 'workflows' if 'workflows' in d else 'sheets'

new_workflows = [
    dict(
        sheet="WF06 Document & Reporting",
        name="WF06 Document & Reporting",
        objective="Verify the full path from a live conversation to a personalized quote PDF, its delivery, and its appearance in the KPI report",
        precondition="The full stack is running; a conversation with an identified contact and a discussed package exists",
        scenarios=[dict(group="Quote generation and delivery", cases=[
            case("TC-ST-DOC-001", "Sale generates a quote PDF from an active conversation",
                 "1. Sign in as a sale user.\n2. Open the conversation and click Generate Quote.\n3. Wait for the document to become ready.",
                 "A PDF is produced with the contact's name and the discussed package within 30 seconds.",
                 "The conversation has a contact and a proposed package",
                 r1=("Passed", "2026-08-16", "QA1")),
            case("TC-ST-DOC-002", "The generated quote is sent through the same channel",
                 "1. Click Send on the ready document.\n2. Check the conversation timeline.",
                 "A message with the document link appears as an outbound message on the same channel.",
                 "TC-ST-DOC-001 completed",
                 r1=("Passed", "2026-08-16", "QA1")),
            case("TC-ST-DOC-003", "The document appears in the customer's document library",
                 "1. Open /documents and filter by the contact.",
                 "The generated quote is listed with its sent timestamp and channel.",
                 "TC-ST-DOC-002 completed",
                 r1=("Passed", "2026-08-17", "QA1")),
        ]), dict(group="Reporting rollup", cases=[
            case("TC-ST-DOC-004", "The document generation event appears in the daily KPI report",
                 "1. Open /reports for the day the document was generated.",
                 "The documents-generated counter includes the new document.",
                 "TC-ST-DOC-001 completed on the report day",
                 r1=("Passed", "2026-08-17", "QA1")),
            case("TC-ST-DOC-005", "A scheduled weekly report is delivered to the configured recipient",
                 "1. Configure a weekly report schedule.\n2. Advance to the scheduled time.\n3. Check the recipient's notification list.",
                 "A report notification or email is delivered at the scheduled time with the correct date range.",
                 "A report schedule is configured",
                 r1=("Failed", "2026-08-17", "QA1"), r2=("Passed", "2026-08-18", "QA1"),
                 note="Round 1: the scheduler used the server's local time instead of the tenant's configured timezone, so delivery was three hours late. Fixed and retested in round 2.",
                 defect="DEF-106"),
            case("TC-ST-DOC-006", "Report export CSV total matches the dashboard total",
                 "1. Export the same date range as CSV.\n2. Sum the export rows and compare to the dashboard total.",
                 "The two totals match exactly.",
                 "kpi_daily rows exist for the range",
                 r1=("Passed", "2026-08-18", "QA1")),
            case("TC-ST-DOC-007", "Expired document link is not reachable from the report drill-down",
                 "1. Open the report entry for a document generated more than 7 days ago.\n2. Click through to the document link.",
                 "The link shows an expired state instead of streaming the file.",
                 "A document older than the expiry window exists",
                 r1=("Passed", "2026-08-18", "QA1")),
        ])],
    ),
    dict(
        sheet="WF07 Admin & Access Control",
        name="WF07 Admin & Access Control",
        objective="Verify end-to-end RBAC: an admin provisions a role and a user, issues an API key, and every fence holds at the system level",
        precondition="The full stack is running; an admin seed account exists",
        scenarios=[dict(group="Provisioning", cases=[
            case("TC-ST-RBA-001", "Admin creates a custom role and assigns it to a new user",
                 "1. Sign in as tenant admin.\n2. Create a role with only conversations:read.\n3. Create a user with that role.",
                 "The new user is created; the role is attached.",
                 "Permission catalog includes conversations:read",
                 r1=("Passed", "2026-08-16", "QA1")),
            case("TC-ST-RBA-002", "The new user's navigation reflects the restricted role",
                 "1. Sign in as the new user.",
                 "Only the Inbox section is visible; other sections are absent from the navigation.",
                 "TC-ST-RBA-001 completed",
                 r1=("Passed", "2026-08-17", "QA1")),
            case("TC-ST-RBA-003", "The restricted user cannot call a write endpoint outside their role",
                 "1. As the new user, POST /api/leads.",
                 "HTTP 403; no lead row is created.",
                 "TC-ST-RBA-001 completed",
                 r1=("Passed", "2026-08-17", "QA1")),
        ]), dict(group="API keys and audit trail", cases=[
            case("TC-ST-RBA-004", "Admin issues a read-only API key for an integration",
                 "1. Create an API key with scope=read.\n2. Call a read endpoint then a write endpoint with the key.",
                 "The read call succeeds; the write call is rejected with HTTP 403.",
                 "Admin holds api-keys:write",
                 r1=("Passed", "2026-08-18", "QA1")),
            case("TC-ST-RBA-005", "Revoking the API key takes effect on the very next call",
                 "1. Revoke the key from TC-ST-RBA-004.\n2. Immediately retry the read call.",
                 "HTTP 401 on the next call; no grace period is observed.",
                 "TC-ST-RBA-004 completed",
                 r1=("Passed", "2026-08-18", "QA1")),
            case("TC-ST-RBA-006", "Every provisioning action is visible in the audit trail",
                 "1. Open /admin/audit and filter by today.",
                 "Role creation, user creation, key issuance and key revocation each appear with actor and timestamp.",
                 "TC-ST-RBA-001 through 005 completed today",
                 r1=("Failed", "2026-08-18", "QA1"), r2=("Passed", "2026-08-19", "QA1"),
                 note="Round 1: the API key revoke action was not wired to the audit writer, so it was silently missing from the trail. Fixed and retested in round 2.",
                 defect="DEF-107"),
            case("TC-ST-RBA-007", "Deactivating the provisioned user revokes access immediately",
                 "1. Deactivate the user created in TC-ST-RBA-001.\n2. Retry any authenticated call with that user's still-open session.",
                 "The next request is rejected with HTTP 403; the session cannot be used further.",
                 "The user has an open session",
                 r1=("Passed", "2026-08-19", "QA1")),
        ])],
    ),
]

d[key].extend(new_workflows)
save(p, d)
total = sum(sum(len(g['cases']) for g in w['scenarios']) for w in d[key])
print('5.3 workflows:', len(d[key]), 'total cases:', total)

# ---------------------------------------------------------------- 5.4 ----
p = 'scripts/testdoc/content/nfr_test.sample.json'
d = load(p)
d['sheets']['Security']['rows'].extend([
    ["TC-SEC-021", "Data export requires an explicit permission", "Sale role",
     "A sale user without the export permission", "Call GET /api/inbox/conversations/{id}/export.csv",
     "HTTP 403 and no file is streamed", "Medium", "Pass", None,
     "Executed 2026-08-20. The same call succeeded once the export permission was granted."],
    ["TC-SEC-022", "Backup snapshots are encrypted at rest", "Tenant admin",
     "A nightly database backup file on the storage volume",
     "Inspect the backup file directly on disk without the decryption key",
     "The file content is not readable as plain SQL or plain text", "High", "Pass", None,
     "Executed 2026-08-20. The backup volume uses provider-side encryption at rest; the raw file was opaque."],
    ["TC-SEC-023", "Security response headers are present on every page", "Anonymous",
     "The staging deployment behind the public domain",
     "Fetch the main page and an API response and inspect the response headers",
     "Content-Security-Policy, X-Content-Type-Options and X-Frame-Options are present", "Medium", "Pass", None,
     "Executed 2026-08-20. All three headers were present on both the page and the API response."],
    ["TC-SEC-024", "Uploaded document rejects an executable extension", "Content editor",
     "The knowledge base document upload endpoint", "Upload a file renamed to end in .exe",
     "The upload is rejected with a validation error before it reaches storage", "High", "Pass", None,
     "Executed 2026-08-20. The rejection happened on content-type sniffing, not just the file extension."],
    ["TC-SEC-025", "A read-only API key cannot reach a write endpoint by path variation", "Anonymous",
     "An API key issued with scope=read", "Call a write endpoint using an alternate casing and trailing slash",
     "HTTP 403 regardless of the path variation used", "Medium", "Pass", None,
     "Executed 2026-08-20. Three path variations were tried; all were rejected consistently."],
    ["TC-SEC-026", "Concurrent scheduled jobs across tenants do not cross-contaminate data", "Tenant admin",
     "Two tenants each with a due scheduled job at the same minute",
     "Let both schedules fire at the same time and inspect the results written by each",
     "Each job only reads and writes its own tenant's rows", "Critical", "Pass", None,
     "Executed 2026-08-20. Ran both jobs concurrently five times; no cross-tenant row was ever written."],
])
d['sheets']['Performance']['rows'].extend([
    ["TC-PERF-013", "Report export completes within SLA for a year of data", "Manual timing against service logs",
     "One year of kpi_daily rows across five channels", "Under twenty seconds for a full-year CSV export",
     "14 s", "Pass", None, "Measured 2026-08-20 with roughly 1800 daily rows in the export."],
    ["TC-PERF-014", "Webhook ingestion holds up under a burst", "Manual (load script)",
     "Fifty webhook calls submitted within one second", "No HTTP 5xx and no dropped message under the burst",
     "0 errors, 0 dropped", "Pass", None, "Measured 2026-08-20; all fifty payloads were queued and later ingested."],
    ["TC-PERF-015", "Notification delivery latency from event to unread badge", "Manual timing against service logs",
     "An escalation event on a conversation", "Under three seconds from escalation to the unread badge updating",
     "1.8 s", "Pass", None, "Measured 2026-08-20 over ten escalations."],
    ["TC-PERF-016", "PDF render time for a ten-page brochure", "Manual (job centre dialog)",
     "A brochure template with ten content sections", "Under twenty seconds to a ready PDF",
     "16 s", "Pass", None, "Measured 2026-08-20; render ran as a background job without blocking the UI."],
])
save(p, d)
print('5.4:', {k: len(v['rows']) for k, v in d['sheets'].items()})

# ---------------------------------------------------------------- 5.5 ----
p = 'scripts/testdoc/content/uat_test.sample.json'
d = load(p)
d['sheets']['UAT']['rows'].extend([
    ["SC-19", "BF-06", "Personalized quote generated and sent from a live conversation", "Sale",
     "1. The sale user opens a conversation where a package was discussed.\n2. The sale user clicks Generate Quote.\n3. The sale user sends the ready PDF through the same channel.\n4. The sale user opens the document library and finds it under the contact.",
     "A quote reaches the customer inside the same conversation in under a minute, and the sale team can always find what was sent to whom.",
     "High", "Pass",
     "Session on 2026-08-20. The PDF was ready in under thirty seconds and appeared correctly in the document library."],
    ["SC-20", "BF-06", "Weekly report reaches the manager on schedule", "Sale manager",
     "1. The manager configures a weekly KPI report schedule.\n2. The manager waits for the scheduled time.\n3. The manager opens the delivered report and compares it with the live dashboard.",
     "The manager receives a report without asking anyone for it, and the numbers match what the dashboard shows live.",
     "Medium", "Pass",
     "Session on 2026-08-20. The report arrived within the scheduled window and the totals matched exactly."],
    ["SC-21", "BF-07", "New role and API key provisioned for an integration partner", "Tenant admin",
     "1. The administrator creates a read-only role for a reporting integration.\n2. The administrator issues an API key under that role.\n3. The administrator tests the key against a read endpoint and a write endpoint.\n4. The administrator revokes the key once the integration test is done.",
     "An external integration can be given exactly the access it needs, proven safe before real use, and cut off cleanly afterward.",
     "High", "Pass",
     "Session on 2026-08-20. The write attempt was refused as expected and the key stopped working immediately after revocation."],
    ["SC-22", "BF-08", "Analytics review across five channels for the week", "PM",
     "1. The PM opens the omnichannel analytics dashboard for the past seven days.\n2. The PM compares channel totals against the exported CSV.\n3. The PM drills into the channel with the lowest conversion.",
     "The PM can see which channel is underperforming and trust the numbers enough to act on them in the same sitting.",
     "Medium", "Pass",
     "Session on 2026-08-20. The drill-down for the underperforming channel matched the summary total exactly."],
])
d['sheets']['Exploratory']['rows'].extend([
    ["2026-08-20", "QA1", "BF-06 / Document library", "Re-sending a previously generated quote creates a second document row identical to the first instead of reusing it, which makes the library noisy after a few resends. Not a defect on its own, logged for the product owner to decide.", "Minor", None],
    ["2026-08-20", "Tenant admin (pilot)", "BF-07 / Role editor", "Removing the last permission from a custom role is allowed and leaves the role with an empty permission set silently, rather than warning that any user on it will see almost nothing.", "Major", "DEF-205"],
])
save(p, d)
print('5.5:', {k: len(v['rows']) for k, v in d['sheets'].items()})
