from docx import Document
from pathlib import Path

SRC = r"C:\Users\admin\OneDrive\Desktop\New Microsoft Word Document.docx"
doc = Document(SRC)

def set_table(table, data):
    for ri, row_data in enumerate(data):
        if ri < len(table.rows):
            for ci, text in enumerate(row_data):
                if ci < len(table.columns):
                    table.cell(ri, ci).text = str(text)

UC53 = [
    ["Use Case ID & Name", "UC-53 - KPI Report Dashboard (Omnichannel Overview)", "UC-53 - KPI Report Dashboard (Omnichannel Overview)", "UC-53 - KPI Report Dashboard (Omnichannel Overview)"],
    ["Created By", "thanglmhe173199", "Date Created", "09/08/2026"],
    ["Primary Actor", "PM", "Secondary Actor", "AnalyticsAggregationService, AppDbContext (kpi_daily)"],
    ["Description",
     "Allows PM to view an omnichannel KPI dashboard aggregating metrics across all connected platforms (Facebook, Zalo, Instagram, TikTok, YouTube). The system reads pre-aggregated daily KPI data from kpi_daily and presents per-platform and total metrics: Leads, DMs, Replies, RepliedDMs, Conversions, AvgResponseTimeSec, AdSpend, CPL, Revenue.",
     "API: GET /api/analytics/omnichannel?from=&to= (default last 7 days). Response: OmniChannelResponse with rows per platform and a stale flag. Data aggregated by KpiAggregator at 00:30 GMT+7 daily. Frontend renders MetricCards, ChannelKpiGrid, ChannelBars on AnalyticsReportsPage.",
     "API: GET /api/analytics/omnichannel-delta?from=&to=&compare=dod|wow. Response: OmniChannelDeltaResponse with per-metric delta % vs prior period. Compare: dod (day-over-day, shifts back by range length capped at 1 day), wow (week-over-week, shifts back 7 days). Metrics: leads, dms, replies, repliedDms, conversions, adSpend, revenue, avgResponseTimeSec."],
    ["Trigger",
     "PM navigates to Analytics > Reports page. Frontend auto-calls GET /api/analytics/omnichannel and GET /api/analytics/omnichannel-delta.",
     "PM navigates to Analytics > Reports page. Frontend auto-calls GET /api/analytics/omnichannel and GET /api/analytics/omnichannel-delta.",
     "PM navigates to Analytics > Reports page. Frontend auto-calls GET /api/analytics/omnichannel and GET /api/analytics/omnichannel-delta."],
    ["Pre-condition",
     "PRE-1: User authenticated with analytics:read permission.\nPRE-2: At least one day of kpi_daily data exists for the tenant.",
     "PRE-1: User authenticated with analytics:read permission.\nPRE-2: At least one day of kpi_daily data exists for the tenant.",
     "PRE-1: User authenticated with analytics:read permission.\nPRE-2: At least one day of kpi_daily data exists for the tenant."],
    ["Post-condition",
     "POST-1 (Success): Dashboard displays per-platform KPI rows with totals, delta comparisons, stale indicator, and connection status.\nPOST-2 (Stale): If last kpi_daily.created_at > 36 hours ago, dashboard shows Du lieu cu warning badge.\nPOST-3 (Failure): API error displays Alert with toUserFriendlyError message."],
    ["Normal flow",
     "1. PM opens Analytics > Reports page (AnalyticsReportsPage.tsx).\n2. Frontend checks role via canUseFeature(role, analytics.tab.agent) for tab visibility.\n3. Frontend calls GET /api/analytics/omnichannel with date range (default 7d or 30d preset).\n4. AnalyticsAggregationService.GetOmnichannelAsync reads kpi_daily filtered by TenantId, From, To.\n5. System groups rows by Platform, aggregates totals, computes CPL (AdSpend/Leads) per row.\n6. Frontend calls GET /api/analytics/omnichannel-delta with compare=wow.\n7. System computes per-metric delta % vs prior period (7-day shift for wow).\n8. System renders: 4 MetricCards (total DMs, automation rate, response time, ad spend), ChannelBars, FunnelCard, ChannelKpiGrid.\n9. Data auto-refreshes every 60s (omnichannel) and 120s (delta)."],
    ["Alternative flow",
     "AF-1: PM selects 30-day preset -> DateRange becomes today-29 to today.\nAF-2: PM filters by platform -> visibleRows filtered client-side to CHANNELS array.\nAF-3: PM switches tabs (overview/agent/lead) -> safeTab state controls rendering."],
    ["Exceptions",
     "E3.1: API error (timeout, 500) -> Alert tone=error, StatusPill Mat ket noi.\nE4.1: No kpi_daily records -> MetricCards show dash, ChannelBars empty state.\nE4.2: Stale data (>36h) -> StatusPill Du lieu cu warning."],
    ["Priority", "High", "High", "High"],
    ["Frequency of use", "High (daily by PM)", "High (daily by PM)", "High (daily by PM)"],
    ["Business rules",
     "BR-25: kpi_daily aggregation at 00:30 GMT+7 daily.\nBR-26: Stale threshold = 36 hours since last kpi_daily.created_at.\nBR-27: CPL = AdSpend / Leads (null if Leads = 0)."],
    ["Other Information",
     "Source: AnalyticsEndpoints.cs, AnalyticsAggregationService.cs, KpiAggregator.cs, AnalyticsReportsPage.tsx\nDomain: KpiDaily (TenantId, Date, Platform, Leads, Dms, Replies, RepliedDms, Conversions, AvgResponseTimeSec, AdSpend, Revenue)\nRate limit: GeneralPolicy | Permissions: analytics:read"],
]

UC54 = [
    ["Use Case ID & Name", "UC-54 - Funnel Conversion Report", "UC-54 - Funnel Conversion Report", "UC-54 - Funnel Conversion Report"],
    ["Created By", "thanglmhe173199", "Date Created", "09/08/2026"],
    ["Primary Actor", "PM", "Secondary Actor", "AnalyticsAggregationService, AppDbContext (kpi_daily)"],
    ["Description",
     "Allows PM to view funnel conversion pipeline: Leads -> DMs (conversations) -> Replies -> Conversions with per-step conversion rates. Filterable by platform.",
     "API: GET /api/analytics/funnel?from=&to=&platform=. Response: FunnelDto with platform, leads, dms, replies, conversions, dmRate, replyRate, conversionRate. Rates: dmRate = dms/leads, replyRate = replies/dms, conversionRate = conversions/leads.",
     "Frontend renders FunnelCard with horizontal progress bars for each step. Displayed on both overview and lead tabs."],
    ["Trigger",
     "PM opens Analytics > Reports overview or lead tab, triggering the funnel query.",
     "PM opens Analytics > Reports overview or lead tab, triggering the funnel query.",
     "PM opens Analytics > Reports overview or lead tab, triggering the funnel query."],
    ["Pre-condition",
     "PRE-1: User authenticated with analytics:read.\nPRE-2: kpi_daily data exists for requested date range.",
     "PRE-1: User authenticated with analytics:read.\nPRE-2: kpi_daily data exists for requested date range.",
     "PRE-1: User authenticated with analytics:read.\nPRE-2: kpi_daily data exists for requested date range."],
    ["Post-condition",
     "POST-1 (Success): Funnel visualization with 4 steps and conversion rates.\nPOST-2 (No data): Empty state message shown."],
    ["Normal flow",
     "1. PM opens Analytics > Reports (overview or lead tab).\n2. Frontend calls GET /api/analytics/funnel with from, to, platform.\n3. AnalyticsAggregationService.GetFunnelAsync reads kpi_daily for TenantId, From, To, Platform.\n4. System sums leads, dms, replies, conversions across range.\n5. System computes: dmRate = dms/leads, replyRate = replies/dms, conversionRate = conversions/leads.\n6. Returns FunnelDto.\n7. Frontend renders FunnelCard: 4 horizontal bars (Lead=100%, Tin nhan, Phan hoi, Chuyen doi).\n8. Platform label: Tat ca kenh for all, or specific name."],
    ["Alternative flow",
     "AF-1: PM selects specific platform -> platform param passed to API.\nAF-2: PM changes date range (7d/30d) -> funnel recalculates."],
    ["Exceptions",
     "E3.1: API error -> FunnelCard empty state.\nE4.1: No records -> dashed border empty state.\nE4.2: Leads = 0 -> rates return 0.0 (Rate() handles zero)."],
    ["Priority", "Medium", "Medium", "Medium"],
    ["Frequency of use", "Medium (weekly review)", "Medium (weekly review)", "Medium (weekly review)"],
    ["Business rules",
     "BR-25: kpi_daily aggregation at 00:30 GMT+7.\nBR-28: Rates via Rate() method: decimal rounded to 4 places, zero denom = 0.\nBR-29: Platform normalization: trim + lowercase, default all if null/empty."],
    ["Other Information",
     "Source: AnalyticsEndpoints.cs, AnalyticsAggregationService.cs, AnalyticsReportsPage.tsx (FunnelCard)\nEndpoint: GET /api/analytics/funnel"],
]

UC55 = [
    ["Use Case ID & Name", "UC-55 - Sale & AI Performance Report", "UC-55 - Sale & AI Performance Report", "UC-55 - Sale & AI Performance Report"],
    ["Created By", "thanglmhe173199", "Date Created", "09/08/2026"],
    ["Primary Actor", "PM", "Secondary Actor", "AnalyticsAggregationService, AppDbContext (agent_sessions, agent_traces, llm_cost_ledger)"],
    ["Description",
     "Allows PM to view AI Agent performance: session counts, completion rates, quality pass rates, AI token usage, per-agent cost breakdown.",
     "API 1: GET /api/analytics/agent-performance?from=&to=. Response: List<AgentPerformanceDto> (agentId, agentName, sessions, completedSessions, traceCount, completionRate, qualitySamples, passedQualitySamples, qualityPassRate, averageQualityScore). API 2: GET /api/analytics/agent-cost?from=&to=. Response: {from, to, items: List<AgentCostItem>} (agentCode, calls, inputTokens, outputTokens, usd, avgUsdPerCall).",
     "Frontend: 4 MetricCards, AgentTable (sortable), AgentRadar (top 5). Tab requires analytics.tab.agent feature flag."],
    ["Trigger",
     "PM clicks Hieu suat Agent tab. Requires canUseFeature(role, analytics.tab.agent).",
     "PM clicks Hieu suat Agent tab. Requires canUseFeature(role, analytics.tab.agent).",
     "PM clicks Hieu suat Agent tab. Requires canUseFeature(role, analytics.tab.agent)."],
    ["Pre-condition",
     "PRE-1: User authenticated with analytics:read + analytics.tab.agent flag.\nPRE-2: Agent sessions exist for date range.",
     "PRE-1: User authenticated with analytics:read + analytics.tab.agent flag.\nPRE-2: Agent sessions exist for date range.",
     "PRE-1: User authenticated with analytics:read + analytics.tab.agent flag.\nPRE-2: Agent sessions exist for date range."],
    ["Post-condition",
     "POST-1 (Success): Agent performance table and radar displayed.\nPOST-2 (Failure): Empty state if no sessions."],
    ["Normal flow",
     "1. PM clicks Hieu suat Agent tab.\n2. Frontend calls GET /api/analytics/agent-performance with from, to.\n3. GetAgentPerformanceAsync queries agent_sessions with Include(Traces).\n4. Groups by AgentId, resolves name from traces.\n5. Computes: sessions, completed (status=completed), trace count, completion rate, quality samples (phase=quality, JSON {passed, score}).\n6. Frontend calls GET /api/analytics/agent-cost.\n7. System queries llm_cost_ledger grouped by AgentCode, sums tokens/usd.\n8. Renders AgentTable and AgentRadar."],
    ["Alternative flow",
     "AF-1: Date range changed -> both queries re-execute.\nAF-2: No cost data -> trace count shown.\nAF-3: No quality samples -> Chua co mau danh gia."],
    ["Exceptions",
     "E3.1: API error -> Alert shown.\nE4.1: No sessions -> empty table.\nE4.2: JSON parse fails -> sample skipped."],
    ["Priority", "Medium", "Medium", "Medium"],
    ["Frequency of use", "Medium (weekly review)", "Medium (weekly review)", "Medium (weekly review)"],
    ["Business rules",
     "BR-30: Agent name from first non-empty AgentName in traces.\nBR-31: Quality trace: phase=quality, JSON {passed: bool, score?: number}.\nBR-32: Error rate = 100 - completionRate*100. Color: >8% error, >3% warning.\nBR-33: Cost matched by agentCode exact, fallback name.includes()."],
    ["Other Information",
     "Source: AnalyticsEndpoints.cs, AnalyticsAggregationService.cs, AnalyticsReportsPage.tsx\nEndpoints: GET /api/analytics/agent-performance, GET /api/analytics/agent-cost\nRequires: analytics.tab.agent feature flag"],
]

UC56 = [
    ["Use Case ID & Name", "UC-56 - Daily KPI Aggregation (Background Job)", "UC-56 - Daily KPI Aggregation (Background Job)", "UC-56 - Daily KPI Aggregation (Background Job)"],
    ["Created By", "thanglmhe173199", "Date Created", "09/08/2026"],
    ["Primary Actor", "System (automated)", "Secondary Actor", "KpiAggregator, AppDbContext (leads, conversations, messages, ads_campaigns, ads_metrics_dailies, lead_revenues)"],
    ["Description",
     "System aggregates daily KPI metrics per platform at 00:30 GMT+7, reading raw data and writing to kpi_daily. Data pipeline for all analytics endpoints.",
     "KpiAggregator.AggregateDailyAsync: (1) Count leads per SourcePlatform, conversions (stage=customer). (2) Count conversations (DMs) per Platform. (3) RepliedDMs: conversations with outbound message. (4) Replies: outbound messages. (5) AvgResponseTimeSec: inbound->first outbound gap. (6) AdSpend: ads_metrics_dailies JOIN ads_campaigns. (7) Revenue: lead_revenues (Approved, decided_at) JOIN leads.",
     "Platforms: facebook, zalo, instagram, tiktok, youtube + all aggregate. Output: KpiAggregateRow per platform to kpi_daily. Failure: logged to audit_logs, retried next hour."],
    ["Trigger",
     "Cron job at 00:30 GMT+7 daily per tenant.",
     "Cron job at 00:30 GMT+7 daily per tenant.",
     "Cron job at 00:30 GMT+7 daily per tenant."],
    ["Pre-condition",
     "PRE-1: DB operational.\nPRE-2: Raw tables have records for target date.",
     "PRE-1: DB operational.\nPRE-2: Raw tables have records for target date.",
     "PRE-1: DB operational.\nPRE-2: Raw tables have records for target date."],
    ["Post-condition",
     "POST-1 (Success): kpi_daily populated, endpoints read fresh data.\nPOST-2 (Stale): If aggregation fails, >36h -> stale warning.\nPOST-3 (Failure): Logged to audit_logs, retry next hour."],
    ["Normal flow",
     "1. Cron triggers 00:30 GMT+7 per tenant.\n2. KpiAggregator.AggregateDailyAsync(tenantId, metricDate).\n3. Query leads: group by SourcePlatform, count leads/conversions.\n4. Query conversations: group by Platform, count DMs.\n5. RepliedDMs: conversations with outbound message.\n6. Messages: count outbound as Replies, compute AvgResponseTimeSec.\n7. Ads: ads_campaigns JOIN ads_metrics_dailies, sum Spend.\n8. Revenue: lead_revenues (Approved, decided_at) JOIN leads, sum Amount.\n9. Write KpiDaily per platform + all aggregate.\n10. KpiDaily.Record() sets all values."],
    ["Alternative flow",
     "AF-1: SQLite -> client-side date filtering.\nAF-2: Unknown platform -> row created, sorted after supported.\nAF-3: No outbound messages -> RepliedDms=0, AvgResp=null."],
    ["Exceptions",
     "E3.1: DB timeout -> logged, retry next hour.\nE4.1: No data -> zero metrics.\nE4.2: Spend null -> AdSpend null, CPL skipped."],
    ["Priority", "High", "High", "High"],
    ["Frequency of use", "High (automated daily)", "High (automated daily)", "High (automated daily)"],
    ["Business rules",
     "BR-25: Aggregation at 00:30 GMT+7.\nBR-34: AnalyticsOffset = TimeSpan.FromHours(7).\nBR-35: RepliedDms per-conversation, always <= Dms.\nBR-36: Revenue uses decided_at.\nBR-37: Conversion = Leads with Stage == customer."],
    ["Other Information",
     "Source: KpiAggregator.cs, IKpiAggregator.cs, KpiDaily.cs\nWritten: kpi_daily | Read: leads, conversations, messages, ads_campaigns, ads_metrics_dailies, lead_revenues\nTimezone: GMT+7"],
]

UC57 = [
    ["Use Case ID & Name", "UC-57 - Export Analytics Report (CSV/PDF)", "UC-57 - Export Analytics Report (CSV/PDF)", "UC-57 - Export Analytics Report (CSV/PDF)"],
    ["Created By", "thanglmhe173199", "Date Created", "09/08/2026"],
    ["Primary Actor", "PM", "Secondary Actor", "AnalyticsExportService, QuestPDF"],
    ["Description",
     "Export omnichannel KPI data as CSV or PDF. Uses same range/data as omnichannel overview. No Excel support.",
     "API: GET /api/analytics/export?format=csv|pdf&from=&to=. CSV columns: platform, leads, dms, replies, conversions, avg_response_time_sec, ad_spend, cpl. PDF: QuestPDF A4, Calibri, 8-col table.",
     "Frontend: ExportDialog modal, Bang CSV (table_view icon), Ban PDF (picture_as_pdf icon). downloadBlob. File: analytics-{from}-{to}.{format}."],
    ["Trigger",
     "PM clicks Xuat bao cao button on Analytics > Reports header.",
     "PM clicks Xuat bao cao button on Analytics > Reports header.",
     "PM clicks Xuat bao cao button on Analytics > Reports header."],
    ["Pre-condition",
     "PRE-1: User authenticated with analytics:read.\nPRE-2: KPI data exists for range.",
     "PRE-1: User authenticated with analytics:read.\nPRE-2: KPI data exists for range.",
     "PRE-1: User authenticated with analytics:read.\nPRE-2: KPI data exists for range."],
    ["Post-condition",
     "POST-1 (Success): File downloaded.\nPOST-2 (Invalid format): 400 Bad Request.\nPOST-3 (Failure): Error in ExportDialog."],
    ["Normal flow",
     "1. PM clicks Xuat bao cao.\n2. ExportDialog opens with CSV/PDF options.\n3. PM clicks format button.\n4. Frontend calls GET /api/analytics/export.\n5. NormalizeFormat validates csv/pdf.\n6. GetOmnichannelAsync gets rows.\n7. CSV: BuildCsv generates CSV string.\n8. PDF: BuildPdf generates QuestPDF doc (A4, Calibri 9pt).\n9. Returns file as Results.File.\n10. Frontend: Blob -> URL.createObjectURL -> download."],
    ["Alternative flow",
     "AF-1: Huy -> dialog closes.\nAF-2: Exporting -> buttons disabled.\nAF-3: Range changed -> export uses mutation range."],
    ["Exceptions",
     "E3.1: API error -> Alert.\nE4.1: Invalid format -> ArgumentException -> 400.\nE4.2: No records -> empty CSV/PDF."],
    ["Priority", "Medium", "Medium", "Medium"],
    ["Frequency of use", "Medium (weekly sharing)", "Medium (weekly sharing)", "Medium (weekly sharing)"],
    ["Business rules",
     "BR-38: Formats: csv, pdf only.\nBR-39: PDF: QuestPDF Community, A4, Calibri.\nBR-40: CSV: RFC-compliant escaping.\nBR-41: File name: analytics-{yyyyMMdd}-{yyyyMMdd}.{format}."],
    ["Other Information",
     "Source: AnalyticsEndpoints.cs, AnalyticsExportService.cs, AnalyticsReportsPage.tsx\nEndpoint: GET /api/analytics/export | QuestPDF for PDF"],
]

UC58 = [
    ["Use Case ID & Name", "UC-58 - Anomaly Detection Alert (Metric Spike)", "UC-58 - Anomaly Detection Alert (Metric Spike)", "UC-58 - Anomaly Detection Alert (Metric Spike)"],
    ["Created By", "thanglmhe173199", "Date Created", "09/08/2026"],
    ["Primary Actor", "PM (viewing) / System (detecting)", "Secondary Actor", "ReportAgent (gRPC), Math.NET Numerics"],
    ["Description",
     "System detects metric anomalies via z-score on KPI time series. PM views on Lead tab.",
     "API: GET /api/analytics/anomalies?metric=&platform=&zThreshold=3&lookbackDays=14. Response: List<AnomalyDto> (date, platform, metric, value, zScore, isAnomaly). Calls ReportAgent.DetectAnomalyAsync via gRPC. Detection: Math.NET Numerics (mean + stddev), rolling window.",
     "Frontend: AnomalyList on Lead tab, up to 6 points, platform/metric labels, status badge. Default: metric=cpl, zThreshold=3, lookbackDays=14."],
    ["Trigger",
     "PM opens Lead tab, auto-calls GET /api/analytics/anomalies.",
     "PM opens Lead tab, auto-calls GET /api/analytics/anomalies.",
     "PM opens Lead tab, auto-calls GET /api/analytics/anomalies."],
    ["Pre-condition",
     "PRE-1: analytics:read permission.\nPRE-2: kpi_daily for lookbackDays.\nPRE-3: ReportAgent gRPC running.",
     "PRE-1: analytics:read permission.\nPRE-2: kpi_daily for lookbackDays.\nPRE-3: ReportAgent gRPC running.",
     "PRE-1: analytics:read permission.\nPRE-2: kpi_daily for lookbackDays.\nPRE-3: ReportAgent gRPC running."],
    ["Post-condition",
     "POST-1 (Success): Anomaly points with z-scores displayed.\nPOST-2 (No anomalies): Khong co canh bao bat thuong.\nPOST-3 (gRPC error): 400 Bad Request."],
    ["Normal flow",
     "1. PM opens Lead tab.\n2. Frontend calls GET /api/analytics/anomalies?metric=cpl&zThreshold=3&lookbackDays=14.\n3. GetAnomaliesAsync validates metric.\n4. Calls ReportAgent.DetectAnomalyAsync via gRPC.\n5. ReportAgent: z-score = (value-mean)/stddev, flags |z| > threshold.\n6. Returns List<AnomalyDto>.\n7. Frontend renders AnomalyList.\n8. Limited to 6 points."],
    ["Alternative flow",
     "AF-1: Platform changed -> query re-executes.\nAF-2: Metric changed -> query re-executes.\nAF-3: No anomalies -> On dinh badge."],
    ["Exceptions",
     "E3.1: gRPC InvalidArgument -> 400.\nE3.2: ReportAgent unavailable -> error alert.\nE4.1: No data -> empty list.\nE4.2: Empty metric -> 400 metric required."],
    ["Priority", "High", "High", "High"],
    ["Frequency of use", "High (daily monitoring)", "High (daily monitoring)", "High (daily monitoring)"],
    ["Business rules",
     "BR-42: Default z-score threshold = 3.0.\nBR-43: Default lookback = 14 days.\nBR-44: Z-score = (value-mean)/stddev.\nBR-45: |z| > threshold -> isAnomaly.\nBR-46: Skill: anomaly-detection (Math.NET, p95 < 100ms)."],
    ["Other Information",
     "Source: AnalyticsEndpoints.cs, proto/agent_report.proto\nEndpoint: GET /api/analytics/anomalies | Skill: anomaly-detection\nFrontend: AnomalyList on Lead tab"],
]

UC71 = [
    ["Use Case ID & Name", "UC-71 - Lead Forecasting (7-Day Prediction)", "UC-71 - Lead Forecasting (7-Day Prediction)", "UC-71 - Lead Forecasting (7-Day Prediction)"],
    ["Created By", "thanglmhe173199", "Date Created", "09/08/2026"],
    ["Primary Actor", "PM / Sales Lead", "Secondary Actor", "AnalyticsAggregationService, kpi_forecasts, ML.NET TimeSeries SSA"],
    ["Description",
     "View 7-day lead forecast with confidence bounds. ML.NET TimeSeries SSA, cached 24h.",
     "API: GET /api/analytics/forecast?metric=leads&platform=&horizon=7. Response: List<ForecastDto> (date, platform, metric, value, lowerBound, upperBound). Reads kpi_forecasts (24h fresh). If stale, re-generated via ML.NET SSA (window=14, series=60).",
     "Frontend: ForecastCard on Lead tab, SVG line chart (420x160). StatusPill: fresh/stale."],
    ["Trigger",
     "PM opens Lead tab, auto-calls GET /api/analytics/forecast.",
     "PM opens Lead tab, auto-calls GET /api/analytics/forecast.",
     "PM opens Lead tab, auto-calls GET /api/analytics/forecast."],
    ["Pre-condition",
     "PRE-1: analytics:read.\nPRE-2: kpi_daily >= 60 days.\nPRE-3: kpi_forecasts fresh or ML.NET can generate.",
     "PRE-1: analytics:read.\nPRE-2: kpi_daily >= 60 days.\nPRE-3: kpi_forecasts fresh or ML.NET can generate.",
     "PRE-1: analytics:read.\nPRE-2: kpi_daily >= 60 days.\nPRE-3: kpi_forecasts fresh or ML.NET can generate."],
    ["Post-condition",
     "POST-1 (Success): 7-day forecast chart with bounds.\nPOST-2 (Empty): Chua co du lieu.\nPOST-3 (Fresh): Moi cap nhat."],
    ["Normal flow",
     "1. PM opens Lead tab.\n2. Frontend calls GET /api/analytics/forecast?metric=leads&platform=all&horizon=7.\n3. GetForecastAsync queries kpi_forecasts.\n4. Filters: TenantId, Platform, Metric, GeneratedAt >= now-24h.\n5. Orders by ForecastDate asc, takes top 7.\n6. Returns List<ForecastDto>.\n7. ForecastCard: SVG polyline with date labels."],
    ["Alternative flow",
     "AF-1: Platform changed -> recalculates.\nAF-2: Cache >24h -> stale.\nAF-3: Background job regenerates.\nAF-4: Horizon changed -> top N rows."],
    ["Exceptions",
     "E3.1: Empty/stale -> empty state.\nE4.1: <60 days history -> ML.NET cannot train.\nE4.2: Empty metric -> 400."],
    ["Priority", "Medium", "Medium", "Medium"],
    ["Frequency of use", "Medium (weekly planning)", "Medium (weekly planning)", "Medium (weekly planning)"],
    ["Business rules",
     "BR-47: ML.NET SSA: window=14, series=60, per-tenant per-platform.\nBR-48: Cache 24h in kpi_forecasts.\nBR-49: Fresh: GeneratedAt >= now-24h.\nBR-50: Skill: forecast-7day, adapter: IForecaster.\nBR-51: p95 < 500ms for 60 points."],
    ["Other Information",
     "Source: AnalyticsEndpoints.cs, AnalyticsAggregationService.cs, KpiForecast.cs, AnalyticsReportsPage.tsx\nEndpoint: GET /api/analytics/forecast | Skill: forecast-7day\nDomain: KpiForecast (TenantId, Platform, Metric, ForecastDate, Value, LowerBound, UpperBound, GeneratedAt)"],
]

updates = {0: UC53, 1: UC54, 2: UC55, 3: UC56, 4: UC57, 5: UC58, 6: UC71}

for idx, data in updates.items():
    if idx < len(doc.tables):
        set_table(doc.tables[idx], data)
        print(f"OK table {idx}")
    else:
        print(f"WARN table {idx} missing")

doc.save(SRC)
print("Saved.")
