<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Clawbot.Agents.Contracts\Clawbot.Agents.Contracts.csproj" />
    <ProjectReference Include="..\..\shared\Clawbot.SharedKernel\Clawbot.SharedKernel.csproj" />
    <ProjectReference Include="..\..\shared\Clawbot.Domain\Clawbot.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.SemanticKernel" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Clawbot.Agents.Tests" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
